#!/usr/bin/bash

set -e

{ lsmod | grep i2c-dev ; } || modprobe -v i2c-dev
{ lsmod | grep led-ugreen ; } || modprobe -v led-ugreen 

i2c_dev=$(i2cdetect -l | grep "SMBus I801 adapter" | grep -Po "i2c-\d+")

if [ $? = 0 ]; then 
        echo "Found I2C device /dev/${i2c_dev}"
        echo "led-ugreen 0x3a" > /sys/bus/i2c/devices/${i2c_dev}/new_device 2>/dev/null || true
else
        echo "I2C device not found!"
fi
